---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: autogov-caller-workflows
  description: "A caller workflow for use w/ our autogov reuseable workflows; https://github.com/liatrio/autogov-workflows."
  annotations:
    github.com/project-slug: liatrio/autogov-caller-workflows
  tags:
    - autogov
    - automated-governance
    - github-actions
    - caller-workflow
    - workflow
spec:
  owner: "group:default/tag-autogov"
  lifecycle: in-progress
  type: service
