name: Build Blob Caller Workflow

on:
  workflow_dispatch:
  # push:
  #   branches: ['**']
  #   paths-ignore:
  #     - .github/workflows/wf-slack-alert.yaml
  #     - README.md
  #     - renovate.json

permissions: {}

jobs:
  build-blob:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
      artifact-metadata: write
    uses: liatrio/autogov-workflows/.github/workflows/rw-build-blob.yaml@c30bc776b4c842aefa825dee0a479dfe6df4dddf # v0.22.2
    secrets: inherit
    with:
      subject-path: |
        i_am_blob
        i_am_another_blob
      cert-identity: https://github.com/liatrio/autogov-workflows/.github/workflows/rw-attest-blob.yaml@c30bc776b4c842aefa825dee0a479dfe6df4dddf # v0.22.2
