name: Build Blob Caller Workflow

on:
  workflow_dispatch:
  # push:
  #   branches: ['**']
  #   paths-ignore:
  #     - .github/workflows/wf-slack-alert.yaml
  #     - README.md
  #     - catalog-info.yaml
  #     - renovate.json

permissions: {}

jobs:
  build-blob:
    permissions:
      id-token: write
      attestations: write
      contents: write
      actions: read
      artifact-metadata: write
    uses: liatrio/liatrio-gh-autogov-workflows/.github/workflows/rw-build-blob.yaml@34eddd0926555cb2b7982c4b82fc0d691520e2f1 # v0.20.15
    secrets: inherit
    with:
      subject-path: |
        i_am_blob
        i_am_another_blob
      cert-identity: https://github.com/liatrio/liatrio-gh-autogov-workflows/.github/workflows/rw-attest-blob.yaml@34eddd0926555cb2b7982c4b82fc0d691520e2f1 # v0.20.15
