name: Build Image Caller Workflow

on:
  workflow_dispatch:
  push:
    branches: ['**']
    paths-ignore:
      - .github/workflows/wf-slack-alert.yaml
      - README.md
      - renovate.json
  pull_request:
    paths-ignore:
      - .github/workflows/wf-slack-alert.yaml
      - README.md
      - renovate.json

permissions: {}

jobs:
  build-image:
    permissions:
      actions: read
      id-token: write
      attestations: write
      packages: write
      contents: write
      pull-requests: read
      artifact-metadata: write
    uses: liatrio/autogov-workflows/.github/workflows/rw-build-image.yaml@c30bc776b4c842aefa825dee0a479dfe6df4dddf # v0.22.2
    secrets: inherit
    with:
      subject-name: ${{ github.repository }}
      registry: ghcr.io
      cert-identity: https://github.com/liatrio/autogov-workflows/.github/workflows/rw-attest-image.yaml@c30bc776b4c842aefa825dee0a479dfe6df4dddf # v0.22.2
